# Generated by Django 2.2.12 on 2020-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='email_bienvenue_envoye',
            field=models.BooleanField(default=False, verbose_name='message de bienvenue envoyé'),
        ),
    ]
