# Generated by Django 2.2.12 on 2020-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0002_candidat_email_bienvenue_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheidentite',
            name='responsables',
            field=models.ManyToManyField(to='inscrire.ResponsableLegal'),
        ),
    ]
