# Generated by Django 2.2.12 on 2020-05-16 13:10

from django.db import migrations
import inscrire.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0003_ficheidentite_responsables'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inscrireuser',
            managers=[
                ('objects', inscrire.models.user.UserManager()),
            ],
        ),
    ]
