# Generated by Django 2.2.12 on 2020-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0005_etablissement_inscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinscolaire',
            options={'verbose_name': 'bulletin scolaire', 'verbose_name_plural': 'bulletins scolaires'},
        ),
        migrations.AlterModelOptions(
            name='candidat',
            options={'verbose_name': 'candidat', 'verbose_name_plural': 'candidats'},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'commune', 'verbose_name_plural': 'communes'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'verbose_name': 'établissement', 'verbose_name_plural': 'établissements'},
        ),
        migrations.AlterModelOptions(
            name='fichebourse',
            options={'verbose_name': 'fiche bourse', 'verbose_name_plural': 'fiches bourse'},
        ),
        migrations.AlterModelOptions(
            name='fichecesure',
            options={'verbose_name': 'fiche césure', 'verbose_name_plural': 'fiches césure'},
        ),
        migrations.AlterModelOptions(
            name='fichehebergement',
            options={'verbose_name': 'fiche hébergement', 'verbose_name_plural': 'fiches hébergement'},
        ),
        migrations.AlterModelOptions(
            name='ficheidentite',
            options={'verbose_name': 'fiche identité', 'verbose_name_plural': 'fiches identité'},
        ),
        migrations.AlterModelOptions(
            name='ficheinternat',
            options={'verbose_name': 'fiche internat', 'verbose_name_plural': 'fiches internat'},
        ),
        migrations.AlterModelOptions(
            name='fichereglement',
            options={'verbose_name': 'fiche règlement intérieur', 'verbose_name_plural': 'fiches règlement intérieur'},
        ),
        migrations.AlterModelOptions(
            name='fichescolarite',
            options={'verbose_name': 'fiche scolarité', 'verbose_name_plural': 'fiches scolarité'},
        ),
        migrations.AlterModelOptions(
            name='fichescolariteanterieure',
            options={'verbose_name': 'fiche scolarité antérieure', 'verbose_name_plural': 'fiches scolarité antérieure'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'formation', 'verbose_name_plural': 'formations'},
        ),
        migrations.AlterModelOptions(
            name='historiquevoeu',
            options={'verbose_name': 'historique de vœu', 'verbose_name_plural': 'historiques de vœu'},
        ),
        migrations.AlterModelOptions(
            name='mefmatiere',
            options={'verbose_name': 'matière MEF', 'verbose_name_plural': 'matières MEF'},
        ),
        migrations.AlterModelOptions(
            name='mefoption',
            options={'verbose_name': 'option MEF', 'verbose_name_plural': 'options MEF'},
        ),
        migrations.AlterModelOptions(
            name='parcoursupmessageenvoyelog',
            options={'verbose_name': 'message envoyé Parcoursup', 'verbose_name_plural': 'messages envoyés Parcoursup'},
        ),
        migrations.AlterModelOptions(
            name='parcoursupmessagereculog',
            options={'verbose_name': 'message reçu Parcoursup', 'verbose_name_plural': 'messages reçus Parcoursup'},
        ),
        migrations.AlterModelOptions(
            name='parcoursupuser',
            options={'verbose_name': 'utilisateur Parcoursup', 'verbose_name_plural': 'utilisateurs Parcoursup'},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'pays', 'verbose_name_plural': 'pays'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'profession', 'verbose_name_plural': 'professions'},
        ),
        migrations.AlterModelOptions(
            name='responsablelegal',
            options={'verbose_name': 'responsable légal', 'verbose_name_plural': 'responsables légaux'},
        ),
        migrations.AlterModelOptions(
            name='voeu',
            options={'verbose_name': 'vœu', 'verbose_name_plural': 'vœux'},
        ),
    ]
