# Generated by Django 2.2.12 on 2020-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0006_verbosenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Adresse de contact proposée aux candidats', max_length=254, verbose_name='adresse e-mail'),
        ),
    ]
