# Generated by Django 2.2.12 on 2020-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0007_email_etab_facultatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='inscriptions',
            field=models.BooleanField(default=False, help_text="Indique s'il s'agit d'un établissement dont le site actuel gère les inscriptions"),
        ),
    ]
