# Generated by Django 2.2.12 on 2020-05-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0011_etablissement_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscrire.Commune'),
        ),
    ]
