# Generated by Django 2.2.12 on 2020-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0012_etablissement_communenulle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['numero_uai'], 'verbose_name': 'établissement', 'verbose_name_plural': 'établissements'},
        ),
        migrations.RemoveField(
            model_name='formation',
            name='groupe_parcoursup',
        ),
        migrations.RemoveField(
            model_name='mefmatiere',
            name='code_gestion',
        ),
        migrations.AlterField(
            model_name='formation',
            name='code_parcoursup',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('code_mef', 'etablissement'), name='code_mef_unique'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('code_parcoursup', 'etablissement'), name='code_parcoursup_unique'),
        ),
    ]
