# Generated by Django 2.2.13 on 2020-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0014_mefoption_inscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='bac_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
