# Generated by Django 2.2.13 on 2020-06-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0015_bacserie_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheidentite',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ficheidentite',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ficheidentite_residence', to='inscrire.Pays'),
        ),
        migrations.AddField(
            model_name='ficheidentite',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone personnel'),
        ),
        migrations.AddField(
            model_name='ficheidentite',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ficheidentite_residence', to='inscrire.Commune'),
        ),
        migrations.AlterField(
            model_name='ficheidentite',
            name='commune_naissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ficheidentite_naissance', to='inscrire.Commune'),
        ),
        migrations.AlterField(
            model_name='ficheidentite',
            name='pays_naissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ficheidentite_naissance', to='inscrire.Pays'),
        ),
    ]
