# Generated by Django 2.2.13 on 2020-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0016_ficheidentite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mefoption',
            name='inscriptions',
            field=models.BooleanField(default=False, help_text="Indique si l'option est présentée aux candidats afin qu'ils la choisissent lors de l'inscription."),
        ),
    ]
