# Generated by Django 2.2 on 2020-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0017_mefoption_default_inscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Adresse de contact proposée aux candidats pour cette formation', max_length=254, verbose_name='adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Adresse de contact proposée aux candidats si aucune adresse n'est renseignée pour une formation", max_length=254, verbose_name='adresse e-mail par défaut'),
        ),
    ]
