# Generated by Django 2.2.4 on 2020-06-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0018_auto_20200612_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectFiches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheidentite', models.BooleanField(blank=True, default=True)),
                ('fichescolariteanterieure', models.BooleanField(blank=True, default=True)),
                ('fichescolarite', models.BooleanField(blank=True, default=True)),
                ('fichehebergement', models.BooleanField(blank=True, default=True)),
                ('ficheinternat', models.BooleanField(blank=True, default=True)),
                ('fichecesure', models.BooleanField(blank=True, default=True)),
                ('fichebourse', models.BooleanField(blank=True, default=True)),
                ('fichereglement', models.BooleanField(blank=True, default=True)),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscrire.Etablissement')),
            ],
        ),
    ]
