# Generated by Django 2.2.13 on 2020-06-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0020_pays_num_insee'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablelegal',
            name='lien',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'père'), (1, 'mère'), (2, 'tuteur'), (3, 'autre')], null=True),
        ),
        migrations.AddField(
            model_name='responsablelegal',
            name='lien_precision',
            field=models.CharField(blank=True, default='', help_text='Lorsque vous choisissez le cas «\xa0autre\xa0» en lien de parenté, merci de préciser ici la nature de lien.', max_length=50, verbose_name='précision autre lien'),
        ),
    ]
