# Generated by Django 2.2.13 on 2020-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0021_responsable_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'homme'), (2, 'femme')], null=True),
        ),
        migrations.AlterField(
            model_name='responsablelegal',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'homme'), (2, 'femme')], null=True),
        ),
    ]
