# Generated by Django 2.2.13 on 2020-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0022_genre_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablelegal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
