# Generated by Django 2.2 on 2020-06-18 13:41

from django.db import migrations, models
import inscrire.models.formation


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inscrire', '0023_responsablelegal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='fiches',
            field=models.ManyToManyField(limit_choices_to=inscrire.models.formation.Etablissement.fiches_limit, to='contenttypes.ContentType'),
        ),
        migrations.DeleteModel(
            name='SelectFiches',
        ),
    ]
