# Generated by Django 2.2 on 2020-06-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0024_auto_20200618_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalite', models.PositiveSmallIntegerField(choices=[(1, 'obligatoire'), (2, 'facultative')], verbose_name='modalité')),
                ('nom', models.CharField(max_length=100)),
                ('etablissement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscrire.Etablissement')),
                ('formation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscrire.Formation')),
            ],
        ),
        migrations.CreateModel(
            name='FichePieceJustificative',
            fields=[
                ('fiche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inscrire.Fiche')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.Formation')),
                ('pieces_recues', models.ManyToManyField(blank=True, to='inscrire.PieceJustificative')),
            ],
            options={
                'verbose_name': 'fiche pièces justificatives',
                'verbose_name_plural': 'fiches pièces justificatives',
            },
            bases=('inscrire.fiche',),
        ),
        migrations.AddConstraint(
            model_name='piecejustificative',
            constraint=models.CheckConstraint(check=models.Q(('etablissement__isnull', True), ('formation__isnull', True), _negated=True), name='formation_ou_etablissement_obligatoire'),
        ),
        migrations.AddConstraint(
            model_name='piecejustificative',
            constraint=models.CheckConstraint(check=models.Q(('etablissement__isnull', True), ('formation__isnull', True), _connector='OR'), name='formation_ou_etablissement_exclusifs'),
        ),
    ]
