# Generated by Django 2.2 on 2020-06-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inscrire', '0026_piecesjustificatives_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampExclu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=255)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='champs_exclus',
            field=models.ManyToManyField(to='inscrire.ChampExclu'),
        ),
    ]
