# Generated by Django 2.2 on 2020-06-22 13:24

from django.db import migrations, models
import inscrire.models.formation


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0027_auto_20200621_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='mefoption',
            name='detail',
            field=models.CharField(blank=True, default='', help_text='Précision éventuelle (débutant, continuant, ...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='champs_exclus',
            field=models.ManyToManyField(help_text='Sélectionnez les champs dont vous ne voulez pas.</br>', to='inscrire.ChampExclu'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='fiches',
            field=models.ManyToManyField(help_text='Sélectionnez les fiches à inclure.</br>', limit_choices_to=inscrire.models.formation.Etablissement.fiches_limit, to='contenttypes.ContentType'),
        ),
    ]
