# Generated by Django 2.2 on 2020-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0028_auto_20200622_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='adresse',
            field=models.TextField(default=''),
        ),
    ]
