# Generated by Django 2.2 on 2020-06-22 17:53

from django.db import migrations, models
import django.db.models.deletion
import inscrire.models.fiches


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inscrire', '0029_etablissement_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejustificative',
            name='descriptif',
            field=models.TextField(default='', help_text="Précisez éventuellement la nature de la pièce et/ou le mode d'expédition"),
        ),
        migrations.AlterField(
            model_name='piecejustificative',
            name='email_specifique',
            field=models.EmailField(blank=True, default='', help_text='Eventuellement, adresse spécifique à laquelle le candidat doit envoyer cette pièce justificative', max_length=254, verbose_name='adresse e-mail pour cette pièce'),
        ),
        migrations.CreateModel(
            name='EnteteFiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(default='')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscrire.Etablissement')),
                ('fiche', models.ForeignKey(limit_choices_to=inscrire.models.fiches.EnteteFiche.fiches_limit, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscrire.Formation')),
            ],
        ),
    ]
