# Generated by Django 2.2 on 2020-06-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0030_auto_20200622_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecejustificative',
            name='descriptif',
        ),
        migrations.RemoveField(
            model_name='piecejustificative',
            name='email_specifique',
        ),
    ]
