# Generated by Django 2.2 on 2020-06-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0033_etablissement_email_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePieceJustificativeSuivi',
            fields=[
                ('fichepiecejustificative_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inscrire.FichePieceJustificative')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inscrire.fichepiecejustificative',),
        ),
    ]
