# Generated by Django 2.2.4 on 2020-06-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0034_fichepiecejustificativesuivi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichepiecejustificative',
            options={'verbose_name': 'fiche pièces justificatives -- envoi', 'verbose_name_plural': 'fiches pièces justificatives -- envoi'},
        ),
        migrations.DeleteModel(
            name='FichePieceJustificativeSuivi',
        ),
    ]
