# Generated by Django 2.2.4 on 2020-06-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0035_auto_20200626_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePieceJustificativeSuivi',
            fields=[
                ('fiche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inscrire.Fiche')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.Formation')),
                ('pieces_recues', models.ManyToManyField(blank=True, to='inscrire.PieceJustificative')),
            ],
            options={
                'verbose_name': 'fiche pièces justificatives -- suivi',
                'verbose_name_plural': 'fiches pièces justificatives -- suivi',
            },
            bases=('inscrire.fiche',),
        ),
    ]
