# Generated by Django 2.2.4 on 2020-06-27 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0036_fichepiecejustificativesuivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
