# Generated by Django 2.2.13 on 2020-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0037_auto_20200627_0756'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voeu',
            constraint=models.UniqueConstraint(condition=models.Q(etat__in=(1, 2)), fields=('candidat',), name='unique_voeu_accepte'),
        ),
    ]
