# Generated by Django 2.2 on 2020-06-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0038_contrainte_voeu_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='sujet_email_pieces_justificatives',
            field=models.CharField(default='', max_length=100),
        ),
    ]
