# Generated by Django 2.2 on 2020-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0040_auto_20200713_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='inscription_administrative_confirmee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidat',
            name='inscription_administrative_message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='etat_dossier',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Édition'), (2, 'Complet'), (3, 'Terminé'), (4, 'Démission')], default=None, help_text="N'envoyer qu'aux candidats dont le dossier est dans l'état indiqué", null=True),
        ),
    ]
