# Generated by Django 2.2 on 2020-08-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscrire', '0041_auto_20200716_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='voeu',
            name='_classement',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_parcoursup', models.IntegerField()),
                ('classement', models.PositiveSmallIntegerField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscrire.Formation')),
            ],
        ),
    ]
